#Bashtop theme with Piink colors
#by Emma <jean.michel.lesatanique@gmail.com>

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#00"

# Main text color
theme[main_fg]="#b01095"

# Title color for boxes
theme[title]="#bf1fa7"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#f72585"

# Background color of selected item in processes box
theme[selected_bg]="#b8174c"

# Foreground color of selected item in processes box
theme[selected_fg]="#ff"

# Color of inactive/disabled text
theme[inactive_fg]="#40"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#ff00ff"

# Cpu box outline color
theme[cpu_box]="#00bbf9"

# Memory/disks box outline color
theme[mem_box]="#9659de"

# Net up/down box outline color
theme[net_box]="#f15bb5"

# Processes box outline color
theme[proc_box]="#feef8c"

# Box divider line and small boxes line color
theme[div_line]="#50"

# Temperature graph colors
theme[temp_start]="#367bf0"
theme[temp_mid]="#b8174c"
theme[temp_end]="#d41919"

# CPU graph colors
theme[cpu_start]="#682080"
theme[cpu_mid]="#d040ff"
theme[cpu_end]="#e8a0ff"

# Mem/Disk free meter
theme[free_start]="#9a6dce"
theme[free_mid]="#560bad"
theme[free_end]="#2b0657"

# Mem/Disk cached meter
theme[cached_start]="#2656a8"
theme[cached_mid]="#4aaee6"
theme[cached_end]="#23bac2"

# Mem/Disk available meter
theme[available_start]="#feef8c"
theme[available_mid]="#fee440"
theme[available_end]="#988926"

# Mem/Disk used meter
theme[used_start]="#7747b2"
theme[used_mid]="#9559de"
theme[used_end]="#4b2d6f"

# Download graph colors
theme[download_start]="#266499"
theme[download_mid]="#40a7ff"
theme[download_end]="#8ccaff"

# Upload graph colors
theme[upload_start]="#941650"
theme[upload_mid]="#f72585"
theme[upload_end]="#fa7cb6"
